In [49]:
import pandas as pd
# Read the CSV files
results_df = pd.read_csv("results.csv")

results_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
0,50,50,0.4,0.25,10,0.01,0.5,0.2,0.10,0.1,33.359651,33.866149,2025-01-30 20:33:25
1,50,50,0.4,0.25,10,0.05,0.5,0.2,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
2,30,40,0.4,0.25,5,0.01,0.8,0.2,0.10,0.1,32.798641,33.418512,2025-01-30 20:40:21
3,30,40,0.3,0.25,5,0.10,0.8,0.2,0.10,0.1,31.697887,32.484707,2025-01-30 20:54:26
4,30,40,0.3,0.25,5,0.30,0.8,0.2,0.10,0.1,32.501605,33.081095,2025-01-30 21:44:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,100,20,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.827533,5.928053,2025-02-15 20:05:00
145,100,20,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.809872,5.924145,2025-02-15 20:35:50
146,50,500,0.6,0.25,4,0.01,0.5,0.2,0.21,0.1,4.988684,5.063692,2025-02-15 20:42:45
147,100,500,0.6,0.25,4,0.01,0.8,0.2,0.01,0.1,3.504411,3.521500,2025-02-15 20:52:52
148,100,200,0.8,0.25,4,0.01,0.8,0.2,0.01,0.1,4.298415,4.313342,2025-02-15 20:57:33

In [33]:
sorted_df = results_df.sort_values(by="best_fitness", ascending=True)
sorted_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
36,100,500,0.6,0.25,5,0.01,0.80,0.20,0.01,0.1,3.402483,3.415809,2025-02-14 13:53:50
29,100,500,0.6,0.25,5,0.01,0.80,0.20,0.01,0.1,3.485530,3.496258,2025-02-03 23:39:39
37,100,500,0.6,0.10,5,0.50,0.80,0.30,0.50,0.1,3.815436,3.954106,2025-02-14 14:01:46
30,100,500,0.6,0.10,5,0.50,0.80,0.30,0.50,0.1,3.885733,4.009497,2025-02-03 23:47:40
25,25,500,0.6,0.25,2,0.30,0.50,0.05,0.30,0.1,4.327443,4.356099,2025-01-31 01:50:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,20,40,0.4,0.05,2,0.33,0.27,0.20,0.10,0.1,33.536611,34.044042,2025-01-30 23:02:14
1,50,50,0.4,0.25,10,0.05,0.50,0.20,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
131,20,40,0.4,0.05,2,0.33,0.23,0.20,0.33,0.1,33.573782,33.962401,2025-01-31 00:19:14
22,25,30,0.6,0.25,2,0.30,0.50,0.05,0.30,0.1,33.599354,33.937279,2025-01-31 01:45:29
61,20,40,0.4,0.80,5,0.01,0.50,0.20,0.10,0.1,33.695860,34.087188,2025-01-30 21:41:41

In [32]:
latest_df = sorted_df.sort_values(by="timestamp", ascending=False)   
latest_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
144,100,20,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.827533,5.928053,2025-02-15 20:05:00
143,100,50,0.6,0.25,10,0.01,0.5,0.2,0.21,0.1,5.457843,5.524301,2025-02-15 20:01:23
40,50,20,0.4,0.10,4,0.10,0.8,0.4,0.40,0.1,32.945978,33.858875,2025-02-15 10:54:24
39,100,50,0.6,0.25,5,0.01,0.8,0.2,0.01,0.1,5.005000,5.021572,2025-02-15 10:48:35
38,100,50,0.6,0.25,5,0.01,0.8,0.2,0.01,0.1,4.871515,4.899884,2025-02-15 10:45:17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,30,40,0.4,0.25,5,0.01,0.5,0.2,0.10,0.1,33.318269,33.966886,2025-01-30 20:52:47
41,30,40,0.4,0.25,5,0.01,0.8,0.2,0.10,0.1,31.943082,32.715915,2025-01-30 20:49:34
2,30,40,0.4,0.25,5,0.01,0.8,0.2,0.10,0.1,32.798641,33.418512,2025-01-30 20:40:21
1,50,50,0.4,0.25,10,0.05,0.5,0.2,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
0,50,50,0.4,0.25,10,0.01,0.5,0.2,0.10,0.1,33.359651,33.866149,2025-01-30 20:33:25

In [37]:
results0_df = pd.read_csv("GenRec0Results.csv")
results0_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp
0,100,50,0.8,0.25,4,0.01,0.8,0.2,0.01,0.1,5.089249,5.108679,5.709359,2025-02-17 00:55:32

In [38]:
sorted0_df = results_df.sort_values(by="best_fitness", ascending=True)
sorted0_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp
0,100,50,0.8,0.25,4,0.01,0.8,0.2,0.01,0.1,5.089249,5.108679,5.709359,2025-02-17 00:55:32

In [41]:
results1_df = pd.read_csv("GenRec1Results.csv")
results1_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp
0,20,20,0.4,0.1,4,0.10,0.8,0.4,0.4,0.1,32.403075,32.924089,34.532178,2025-02-17 01:02:40
1,20,20,0.4,0.1,4,0.05,0.8,0.4,0.4,0.1,32.876474,33.465806,33.797322,2025-02-17 01:14:52

In [43]:
sorted1_df = results1_df.sort_values(by="best_fitness", ascending=True)
sorted1_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,test_score,timestamp
0,20,20,0.4,0.1,4,0.10,0.8,0.4,0.4,0.1,32.403075,32.924089,34.532178,2025-02-17 01:02:40
1,20,20,0.4,0.1,4,0.05,0.8,0.4,0.4,0.1,32.876474,33.465806,33.797322,2025-02-17 01:14:52