In [ ]:
import pandas as pd
# Read the CSV files
results_df = pd.read_csv("results.csv")

results_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
0,50,50,0.4,0.25,10,0.01,0.50,0.2,0.10,0.1,33.359651,33.866149,2025-01-30 20:33:25
1,50,50,0.4,0.25,10,0.05,0.50,0.2,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
2,30,40,0.4,0.25,5,0.01,0.80,0.2,0.10,0.1,32.798641,33.418512,2025-01-30 20:40:21
3,30,40,0.3,0.25,5,0.10,0.80,0.2,0.10,0.1,31.697887,32.484707,2025-01-30 20:54:26
4,30,40,0.3,0.25,5,0.30,0.80,0.2,0.10,0.1,32.501605,33.081095,2025-01-30 21:44:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,20,40,0.4,0.05,2,0.33,0.23,0.2,0.49,0.1,33.172409,33.631685,2025-01-31 00:34:36
139,20,40,0.4,0.05,2,0.33,0.23,0.2,0.51,0.1,33.172934,33.637344,2025-01-31 00:36:45
140,20,150,0.3,0.05,2,0.33,0.23,0.2,0.03,0.1,33.127834,33.368920,2025-01-31 00:45:50
141,20,150,0.3,0.05,2,0.33,0.23,0.2,0.03,0.1,32.806848,33.039127,2025-01-31 01:05:47
142,20,150,0.3,0.25,5,0.01,0.80,0.2,0.01,0.1,30.452496,30.608713,2025-01-31 01:12:21

In [ ]:
sorted_df = results_df.sort_values(by="best_fitness", ascending=True)
sorted_df

,population_size,generations,sample_ratio,similarity_penalty,elitism,lamda_reg,split_ratio,noise_scale,mutation_rate,scale,best_fitness,avg_fitness,timestamp
36,100,500,0.6,0.25,5,0.01,0.80,0.20,0.01,0.1,3.402483,3.415809,2025-02-14 13:53:50
29,100,500,0.6,0.25,5,0.01,0.80,0.20,0.01,0.1,3.485530,3.496258,2025-02-03 23:39:39
37,100,500,0.6,0.10,5,0.50,0.80,0.30,0.50,0.1,3.815436,3.954106,2025-02-14 14:01:46
30,100,500,0.6,0.10,5,0.50,0.80,0.30,0.50,0.1,3.885733,4.009497,2025-02-03 23:47:40
25,25,500,0.6,0.25,2,0.30,0.50,0.05,0.30,0.1,4.327443,4.356099,2025-01-31 01:50:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,20,40,0.4,0.05,2,0.33,0.27,0.20,0.10,0.1,33.536611,34.044042,2025-01-30 23:02:14
1,50,50,0.4,0.25,10,0.05,0.50,0.20,0.10,0.1,33.544466,33.996070,2025-01-30 20:36:49
131,20,40,0.4,0.05,2,0.33,0.23,0.20,0.33,0.1,33.573782,33.962401,2025-01-31 00:19:14
22,25,30,0.6,0.25,2,0.30,0.50,0.05,0.30,0.1,33.599354,33.937279,2025-01-31 01:45:29
61,20,40,0.4,0.80,5,0.01,0.50,0.20,0.10,0.1,33.695860,34.087188,2025-01-30 21:41:41